services:
  backend:
    build:
      context: ./BackEnd
    ports:
      - "8060:8060"
    environment:
      - MONGO_URI=mongodb://mongo:27017/fantrade
    depends_on:
      - mongo
    volumes:
      - ./BackEnd:/usr/src/app
    command: npm start

  frontend:
    build:
      context: ./front-end
    ports:
      - "3000:3000"
    volumes:
      - ./front-end:/usr/src/app
    depends_on:
      - backend
    command: npm start

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
